### ISSUE TITLE
Error when 

### ISSUE THREAD

**Issue by Mehdi-Bl** [dskaggs/vagrant-centos-lucee#11]
Hi,

When I tried running it on windows 10 I got

___________________________
==> default: ========================================================================
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Starting httpd:
==> default: httpd: apr_sockaddr_info_get() failed for vagrant-centos66
==> default: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1 for ServerName
==> default: [Fri Jan 27 04:14:37 2017] [warn] NameVirtualHost *:80 has no VirtualHosts
==> default: [FAILED]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
___________________________

And it failed.

M B

**Comment by dskaggs** [comment]
@MBlagui I am no longer maintaining this project. I suggest you look to https://github.com/Ortus-Solutions/vagrant-centos-lucee for a more updated/maintained version.

**Comment by dskaggs** [comment]
Closing as this project is no longer being maintained.
