### ISSUE TITLE
Newer version of MySQL

### ISSUE THREAD

**Issue by davemerrill** [dskaggs/vagrant-centos-lucee#3]
(Thanks for this!)

How hard would it be to make a variation of this with a newer version of MySQL? Say 5.6?

**Comment by dskaggs** [comment]
Funny you should say that. I just had to do that very thing on a (private) Vagrant box for one of my clients. It's not difficult at all. Our installs run MySQL 5.5. I just had to look up the command line commands to install the newer version from somewhere other than the default yum repos. Give me a few minutes and I'll throw something together in another branch for testing.

**Comment by dskaggs** [comment]
Added the 'develop' branch that installs MySQL 5.5. Give that a shot and see if it works for you.

**Comment by davemerrill** [comment]
Thank you sir, that was fast!

I just asked about this
https://groups.google.com/forum/#!topic/lucee/bNfxdwBl8Z8 on the Lucee
list, Brad suggested that I do it myself and submit a pull request, but as
I said there, I just installed Vagrant today, have never used it at all, so
you jumping on this is most welcome.

Take a look at that thread, looks like Brad has a fork he's been developing
https://groups.google.com/forum/#!topic/lucee/bNfxdwBl8Z8 with some
additional features.

Thanks again,
Dave

**Comment by dskaggs** [comment]
Yep...I've been meaning to pull the relevant bits out of that repo and update this one. I just added several tickets with references to various places of that repo.

**Comment by davemerrill** [comment]
So. Please excuse my massive ignorance about pretty much every aspect of this -- brand new to vagrant, not much of a linux guy, or super familiar with VirtualBox, though glad to be beginning to spin up a tiny bit on all -- but some of this didn't work for me I think.

After some hiccups that I think I got past, and really quite a long time of downloading and installing components, the cmd prompt ended by listing out some connection info for use, and was able to serve cfm pages from the mapped root directory.

However, I think the MySQL install failed. This is from the cmd prompt:

> Retrieving https://mirror.webtatic.com/yum/el6/latest.rpm
> webtatic-release
> Error: mysql55w-libs conflicts with mysql-libs-5.1.73-5.el6_6.x86_64
> mysqld: unrecognized service
> error reading information on service mysqld: No such file or direct

Webmin's MySQL page says:

> The MySQL admin program /usr/bin/mysqladmin was not found on your system
> The MySQL administration program package can be automatically installed by Webmin. Click here to have it downloaded and installed using YUM.

I've tried to connect to it from the host machine with no luck, and while there are other possible reasons for that, I think it's actually not installed. I have the log of the vagrant actions if that'd be helpful.

What's the right move from there?

Also this:

> [warn] NameVirtualHost *:80 has no VirtualHosts

That just means I need to set up virtual roots in Apache config on that VM, right?

And one last question: What's the mechanism that syncs the www dir on the VM with the corresponding directory on the host? I'm asking because it's important to me to know if it's safe to put a Windows directory junction in that host directory. Windows junctions have some ["unfortunate" properties](http://devtidbits.com/2009/09/07/windows-file-junctions-symbolic-links-and-hard-links/), so certain actions on the link affect the original. The junction I want to create is to the source code of an important project that I'd like available on the VM, but not if the actual source could be compromised. (Yes it's under source control etc, but still.)

Thanks again for your help, and please let me know if this is inappropriate conversation to have here. Just thought it might help move this project forward, and maybe help others with some of these same questions.

**Comment by dskaggs** [comment]
Yep, you're correct. I ran into the MySQL issue on the repo I'm doing for my client and forgot to come back over here and add the command. Pull the latest develop and run it again.

You should be able to safely ignore the Apache warning.

In the VagrantFile around line 21 is where the "www" directory in this project is mapped to "/var/www/sites" directory inside the VM. That uses the underlying virtual machine program to link the two directories (in this case VirtualBox's shared folder feature).

I'm afraid I can't help you on the Windows junctions question as I'm a Mac user. The Apache config file has FollowSymLinks enabled so maybe that's enough?

If you run into questions you can usually find me on the CFML Slack channel (http://cfml.slack.com). If you haven't signed up yet, you can auto generate your invite here: http://cfml-slack.herokuapp.com/

**Comment by dskaggs** [comment]
Closing as this project is no longer being maintained.
